### ISSUE TITLE
Lamp is not installed on Rasberry Pi Zero

### ISSUE THREAD

**Issue by dcalles** [davidferguson/pibakery-raspbian#1]
I have put the block Install Apache/PHP/MySQL in the On First Boot section and despite the system tries to install it and it doesn't seem to exist any error, any of the mysql, apache, php packages appears in the "sudo dpkg --get-selections" command. 

It appears that the "Set Boot Option to Console", doesn't function either.

![image](https://cloud.githubusercontent.com/assets/3846856/17837435/46097a92-67b3-11e6-9a74-659d491e4123.png)

**Comment by davidferguson** [comment]
This is because the Install Apache/PHP/MySQL block requires a network connection, and from the image you posted it seems that you're connecting to WiFi after you're trying to install LAMP. 

Apologies for not making it clear which block require network access to work, I'm working on an update that will show a globe icon on the block if it needs internet access, which should be pushed out within the next few days.

In the meantime, moving the WiFi block to the start of the First Boot blocks should solve this issue.

For the Boot Option block, that could be because that block will only take effect after a restart. Like blocks that need internet access, I'm working on an update that will show a restart icon on blocks that need a restart to take effect. This should be in the same update as talked about above.

**Comment by dcalles** [comment]
Thanks for the quick response, and for a very excellent work.

**Comment by davidferguson** [comment]
There has now been a block update which shows clearly which blocks need an internet connection to work, and which need a restart to take effect. You should be prompted about this update the next time you open PiBakery, and the latest PiBakery version will have the updated blocks already included.
