### ISSUE TITLE
Version in info.json

### ISSUE THREAD

**Issue by lurch** [davidferguson/pibakery-raspbian#2]
Should https://github.com/davidferguson/pibakery-raspbian/blob/master/info.json say `"version": 1.1`, just like https://github.com/davidferguson/pibakery/blob/master/os/info.json does?
The MD5s in the two corresponding files match up, which is what makes me suspect the versions should too.

**Comment by davidferguson** [comment]
The reason I haven't incremented the version in https://github.com/davidferguson/pibakery-raspbian/blob/master/info.json yet is because as soon as I do, PiBakery will prompt people to do an update. I've chosen not to push out an update yet, as I suspect a new version of Raspbian is on the way very soon from the Raspberry Pi Foundation, and I don't want to push out two in close succession.

**Comment by lurch** [comment]
Fair enough :)

I also believe a new Raspbian is "coming soon", see https://github.com/RPi-Distro/python-gpiozero/pull/415#issuecomment-243466636
