### ISSUE TITLE
Asking for permission after PiBakery is loaded on my mac

### ISSUE THREAD

**Issue by Timon0x31** [davidferguson/pibakery-raspbian#48]
Something just doesn't see right. Downloaded PiBakery and went through the Install. Got the normal message about not being an identified developer and say ok and the program loaded normally.

The problem comes when I actually go to run PiBakery. I'm getting another request for permission to make modifications. This should normally not happen at this point. There is nothing on your web page about this and I'm Leary that the program may had been compromised. Is this normal and why would it be asking for permission at this point.

**Comment by davidferguson** [comment]
This is because writing an SD card requires admin permissions. No changes to your system are actually going to be made, the `permission to make modifications` message is just a generic Apple Admin Password message that I can't change.

When developing PiBakery I had the choice to either require users to enter their admin password upon open or when they clicked the *Write* button in the app. I chose to require it upon open for a few reasons, including:

- Removes requirement of entering password multiple times if multiple SD cards are being written
- Users may try and use PiBakery without knowing the admin password and would get disappointed after creating a custom configuration and *then* being asked for the admin password

Hope this answers your question.

**Comment by Timon0x31** [comment]
Thanks David. 

My main worry was having it ask just ask I open the program. Just wanted to be sure before I proceeded.

Second, I think there is away around that as I don't remember SDFormatter asking that question however I could be wrong.
